### ISSUE TITLE
Izpis none in logičnih vrednosti v bazi ter kodiranje znakov v HTML

### ISSUE THREAD

**Issue by DenisBencic** [DenisBencic/Slovenske-fakultete-PB1#4]
Potreboval bi nekaj napotkov. Zanima me naslednje:

1. Kako bi vrednost None, ki ga vrača baza, izpisal kot prazen niz v HTML-ju? Konkretno imam naslednji primer v spletnem vmesniku. Podobno imam težave z logičnima vrednostima 1 in 0, ki bi ju rad izpisal kot 'da' in 'ne.
![Zajeta slika 3](https://user-images.githubusercontent.com/44201323/104099616-2c35d280-529d-11eb-898e-a33a450b0b5c.PNG)
![Zajeta slika 4](https://user-images.githubusercontent.com/44201323/104099734-33f57700-529d-11eb-8726-7868ca04fc3e.PNG)

2. Pri kodiranju znakov v HTML-ju se zgodi naslednje. Poskusil sem z request.query.unicode, vendar težava še vedno ne izgine:
![Zajeta slika](https://user-images.githubusercontent.com/44201323/104100793-846cd480-529d-11eb-8a96-1dba62c588a6.PNG)
![Zajeta slika 2](https://user-images.githubusercontent.com/44201323/104100840-88005b80-529d-11eb-8f31-c656c351c94e.PNG)

Hvala za Vaš odgovor!

**Comment by jaanos** [comment]
Za zamenjavo `None` s praznim nizom se lahko uporabi npr. `dekan if dekan else ''` (v predlogi lahko to postavita v dvojne zavite oklepaje, tako kot spremenljivke same). 

Da ne bo problemov s šumniki pri podatkih iz obrazcev, bo najbolje, če do njih dostopata npr. z `request.query.iskalni_niz`.

Imam še nekaj pripomb:

* V `spletni_vmesnik.py` imata gnezdene funkcije. Tega ne počnita - vse funkcije za prikaz spletnih strani naj bodo na vrhu (tj., nezamaknjene). Edino tako bodo vse strani takoj dostopne.

* Svetujem, da v predlogah uporabita `rebase`, da se uporabi ena skupna osnova za vse strani (tj., če spreminjata izgled, tega ne bo potrebno početi na vsaki predlogi posebej).

* Poti, ki jih uporabljata v povezavah, naj bodo absolutne (tj., se začnejo z `/`). Tako ne bo potrebno popravljati predlog, če spremenita strukturo poti.

**Comment by DenisBencic** [comment]
S šumniki imam še vedno težave oz. nisem razumel točno kaj mislite. Konkretno `request.query` uporabljam na način kot ga pokaže prof. Pretnar v videoposnetku na povezavi https://www.youtube.com/watch?v=oDexWFRaekU&t=4177s:

```python
@route('/univerze/naziv/rezultati/')
def isci():
    iskalni_niz = request.query['iskalni_niz']
    univerze = isci_univerza_naziv(iskalni_niz)
    return template('rezultati_iskanja_univerze', iskalni_niz = iskalni_niz, univerze = univerze)
```

V kolikor spremenim vrstico `iskalni_niz = request.query['iskalni_niz']` v `iskalni_niz = request.query.'iskalni_niz'`, Python javi sintaktično napako.

Glede `None` vrednosti je sedaj odpravljeno, vendar v kolikor se `None` pojavi znotraj hiperpovezave, nisem prepričan kako to odpraviti: 
```html
<li> <b> Dekan:</b> {{fakulteta[2] if fakulteta[2] else ''}} </li>
<li> <b> Lokacija:</b> <a href="https://www.google.si/maps/place/{{fakulteta[3]}}">{{fakulteta[3]}}</a> </li>
```

Ostali dve pripombi sta bili razumljivi.

**Comment by jaanos** [comment]
Za pridobitev vrednosti polja v obrazcu naredita kar
```python
iskalni_niz = request.query.iskalni_niz
```
\- torej brez navednic.

Kar se tiče manjkajočih podatkov, bo morda celo lepše, če enostavno izpustita celotno vrstico, če podatek manjka, npr.
```jinja
% if fakulteta[2]:
  <li> <b> Dekan:</b> {{fakulteta[2]}} </li>
% end
% if fakulteta[3]:
  <li> <b> Lokacija:</b> <a href="https://www.google.si/maps/place/{{fakulteta[3]}}">{{fakulteta[3]}}</a> </li>
% end
```

Sicer pa svetujem, da svojo kodo sproti committata in nalagata na GitHub (to počnita znotraj VS Code-a in ne z nalaganjem datotek preko brskalnika!), da lahko točno vidimo, kaj se dogaja.

**Comment by DenisBencic** [comment]
Odpravljeno.
